export const Constants = {
    ADD_POLICY_REQUEST = 'policy/ADD_POLICY_REQUEST',
    UPDATE_POLICY_REQUEST = 'policy/UPDATE_POLICY_REQUEST',
    DELETE_POLICY_REQUEST = 'policy/DELETE_POLICY_REQUEST',

    ADD_POLICY_SUCCESS = 'policy/ADD_POLICY_SUCCESS',
    UPDATE_POLICY_SUCCESS = 'policy/UPDATE_POLICY_SUCCESS',
    DELETE_POLICY_SUCCESS = 'policy/DELETE_POLICY_SUCCESS',
    
    ADD_POLICY_FAILURE = 'policy/ADD_POLICY_FAILURE',
    UPDATE_POLICY_FAILURE = 'policy/UPDATE_POLICY_FAILURE',
    DELETE_POLICY_FAILURE = 'policy/DELETE_POLICY_FAILURE'
}