export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_BY_TOKEN_REQUEST = 'LOGIN_BY_TOKEN_REQUEST';
export const LOGIN_BY_TOKEN_SUCCESS = 'LOGIN_BY_TOKEN_SUCCESS';
export const LOGIN_BY_TOKEN_FAILURE = 'LOGIN_BY_TOKEN_FAILURE';